### ISSUE TITLE
Debian testing & Ubuntu 16.10 build issue

### ISSUE THREAD

**Issue by DAP-DarkneSS** [vtyulb/QLiveBittorrent#4]
Hello.

Feel free to reject if abandoned.

libtorrent-rasterbar9-1.1.0-3

[   61s] In file included from src/mainwindow.h:21:0,
[   61s]                  from src/mainwindow.cpp:1:
[   61s] src/torrent.h:26:23: error: 'iterator' in 'class libtorrent::file_storage' does not name a type
[   61s]  typedef file_storage::iterator file_iterator;
[   61s]                        ^~~~~~~~
[   62s] In file included from src/mainwindow.h:21:0,
[   62s]                  from src/main.cpp:1:
[   62s] src/torrent.h:26:23: error: 'iterator' in 'class libtorrent::file_storage' does not name a type
[   62s]  typedef file_storage::iterator file_iterator;
[   62s]                        ^~~~~~~~
[   62s] src/mainwindow.cpp: In destructor 'virtual MainWindow::~MainWindow()':
[   62s] src/mainwindow.cpp:56:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
[   62s]      for (int i = 0; i < v.size(); i++) {
[   62s]                      ~~^~~~~~~~~~
[   62s] src/mainwindow.cpp:58:35: warning: 'void libtorrent::session_handle::pop_alerts(std::deque<libtorrent::alert*>*)' is deprecated [-Wdeprecated-declarations]
[   62s]          session->pop_alerts(&trash);
[   62s]                                    ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:916:8: note: declared here
[   62s]    void pop_alerts(std::deque<alert*>* alerts);
[   62s]         ^~~~~~~~~~
[   62s] src/mainwindow.cpp:66:14: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
[   62s]          std::auto_ptr<alert> holder = session->pop_alert();
[   62s]               ^~~~~~~~
[   62s] In file included from /usr/include/c++/6/memory:81:0,
[   62s]                  from /usr/include/boost/config/no_tr1/memory.hpp:21,
[   62s]                  from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
[   62s]                  from /usr/include/boost/shared_ptr.hpp:17,
[   62s]                  from /usr/include/libtorrent/torrent_handle.hpp:43,
[   62s]                  from src/torrent.h:13,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
[   62s]    template<typename> class auto_ptr;
[   62s]                             ^~~~~~~~
[   62s] src/mainwindow.cpp:66:58: warning: 'std::auto_ptr<libtorrent::alert> libtorrent::session_handle::pop_alert()' is deprecated [-Wdeprecated-declarations]
[   62s]          std::auto_ptr<alert> holder = session->pop_alert();
[   62s]                                                           ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:924:24: note: declared here
[   62s]    std::auto_ptr<alert> pop_alert();
[   62s]                         ^~~~~~~~~
[   62s] src/mainwindow.cpp:78:69: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]          QSettings s(settingsPath + QString::fromStdString(v[i].name()) + ".qlivebittorrent", QSettings::IniFormat);
[   62s]                                                                      ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp:80:58: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]          s.setValue("path", QVariant(mapTorrent[v[i].name()]->downloadPath));
[   62s]                                                           ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp: In member function 'void MainWindow::initSession(QString)':
[   62s] src/mainwindow.cpp:91:63: warning: 'libtorrent::session_settings libtorrent::session_handle::settings() const' is deprecated [-Wdeprecated-declarations]
[   62s]      libtorrent::session_settings settings = session->settings();
[   62s]                                                                ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:810:20: note: declared here
[   62s]    session_settings settings() const;
[   62s]                     ^~~~~~~~
[   62s] src/mainwindow.cpp:95:35: warning: 'void libtorrent::session_handle::set_settings(const libtorrent::session_settings&)' is deprecated [-Wdeprecated-declarations]
[   62s]      session->set_settings(settings);
[   62s]                                    ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:808:8: note: declared here
[   62s]    void set_settings(session_settings const& s);
[   62s]         ^~~~~~~~~~~~
[   62s] src/mainwindow.cpp:96:57: warning: 'void libtorrent::session_handle::set_download_rate_limit(int)' is deprecated [-Wdeprecated-declarations]
[   62s]      session->set_download_rate_limit(rate.toInt() * 1000);
[   62s]                                                          ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:902:8: note: declared here
[   62s]    void set_download_rate_limit(int bytes_per_second);
[   62s]         ^~~~~~~~~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp:97:30: warning: 'void libtorrent::session_handle::set_alert_mask(uint32_t)' is deprecated [-Wdeprecated-declarations]
[   62s]      session->set_alert_mask(0);
[   62s]                               ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:1003:8: note: declared here
[   62s]    void set_alert_mask(boost::uint32_t m);
[   62s]         ^~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp: In member function 'void MainWindow::updateStandartText()':
[   62s] src/mainwindow.cpp:127:38: warning: 'int libtorrent::session_handle::download_rate_limit() const' is deprecated [-Wdeprecated-declarations]
[   62s]      if (session->download_rate_limit() != 0)
[   62s]                                       ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:887:7: note: declared here
[   62s]    int download_rate_limit() const;
[   62s]        ^~~~~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp:128:91: warning: 'int libtorrent::session_handle::download_rate_limit() const' is deprecated [-Wdeprecated-declarations]
[   62s]          text += QString("Download rate limit: %1KB/s\n").arg(session->download_rate_limit() / 1000);
[   62s]                                                                                            ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:887:7: note: declared here
[   62s]    int download_rate_limit() const;
[   62s]        ^~~~~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp: In member function 'void MainWindow::realAddTorrent(QString, QString, QString)':
[   62s] src/mainwindow.cpp:185:99: warning: 'libtorrent::torrent_handle libtorrent::add_magnet_uri(libtorrent::session&, const string&, const libtorrent::add_torrent_params&)' is deprecated [-Wdeprecated-declarations]
[   62s]          const torrent_handle h = libtorrent::add_magnet_uri(*session, torrentFile.toStdString(), p);
[   62s]                                                                                                    ^
[   62s] In file included from src/mainwindow.h:38:0,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/magnet_uri.hpp:67:32: note: declared here
[   62s]   torrent_handle TORRENT_EXPORT add_magnet_uri(session& ses, std::string const& uri
[   62s]                                 ^~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp:187:40: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]          mapTorrent[main->torrent->name()] = main;
[   62s]                                         ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp:190:16: error: no match for 'operator=' (operand types are 'boost::shared_ptr<libtorrent::torrent_info>' and 'libtorrent::torrent_info*')
[   62s]          p.ti = inf;
[   62s]                 ^~~
[   62s] In file included from /usr/include/boost/shared_ptr.hpp:17:0,
[   62s]                  from /usr/include/libtorrent/torrent_handle.hpp:43,
[   62s]                  from src/torrent.h:13,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:524:18: note: candidate: boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(const boost::shared_ptr<T>&) [with T = libtorrent::torrent_info]
[   62s]      shared_ptr & operator=( shared_ptr const & r ) BOOST_NOEXCEPT
[   62s]                   ^~~~~~~~
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:524:18: note:   no known conversion for argument 1 from 'libtorrent::torrent_info*' to 'const boost::shared_ptr<libtorrent::torrent_info>&'
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:533:18: note: candidate: template<class Y> boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(const boost::shared_ptr<Y>&) [with Y = Y; T = libtorrent::torrent_info]
[   62s]      shared_ptr & operator=(shared_ptr<Y> const & r) BOOST_NOEXCEPT
[   62s]                   ^~~~~~~~
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:533:18: note:   template argument deduction/substitution failed:
[   62s] src/mainwindow.cpp:190:16: note:   mismatched types 'const boost::shared_ptr<X>' and 'libtorrent::torrent_info*'
[   62s]          p.ti = inf;
[   62s]                 ^~~
[   62s] In file included from /usr/include/boost/shared_ptr.hpp:17:0,
[   62s]                  from /usr/include/libtorrent/torrent_handle.hpp:43,
[   62s]                  from src/torrent.h:13,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:544:18: note: candidate: template<class Y> boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(std::auto_ptr<_Up>&) [with Y = Y; T = libtorrent::torrent_info]
[   62s]      shared_ptr & operator=( std::auto_ptr<Y> & r )
[   62s]                   ^~~~~~~~
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:544:18: note:   template argument deduction/substitution failed:
[   62s] src/mainwindow.cpp:190:16: note:   mismatched types 'std::auto_ptr<Y>' and 'libtorrent::torrent_info*'
[   62s]          p.ti = inf;
[   62s]                 ^~~
[   62s] In file included from /usr/include/boost/shared_ptr.hpp:17:0,
[   62s]                  from /usr/include/libtorrent/torrent_handle.hpp:43,
[   62s]                  from src/torrent.h:13,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:553:18: note: candidate: template<class Y> boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(std::auto_ptr<_Up>&&) [with Y = Y; T = libtorrent::torrent_info]
[   62s]      shared_ptr & operator=( std::auto_ptr<Y> && r )
[   62s]                   ^~~~~~~~
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:553:18: note:   template argument deduction/substitution failed:
[   62s] src/mainwindow.cpp:190:16: note:   mismatched types 'std::auto_ptr<Y>' and 'libtorrent::torrent_info*'
[   62s]          p.ti = inf;
[   62s]                 ^~~
[   62s] In file included from /usr/include/boost/shared_ptr.hpp:17:0,
[   62s]                  from /usr/include/libtorrent/torrent_handle.hpp:43,
[   62s]                  from src/torrent.h:13,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:575:18: note: candidate: template<class Y, class D> boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(std::unique_ptr<_Up, _Ep>&&) [with Y = Y; D = D; T = libtorrent::torrent_info]
[   62s]      shared_ptr & operator=( std::unique_ptr<Y, D> && r )
[   62s]                   ^~~~~~~~
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:575:18: note:   template argument deduction/substitution failed:
[   62s] src/mainwindow.cpp:190:16: note:   mismatched types 'std::unique_ptr<_Tp, _Dp>' and 'libtorrent::torrent_info*'
[   62s]          p.ti = inf;
[   62s]                 ^~~
[   62s] In file included from /usr/include/boost/shared_ptr.hpp:17:0,
[   62s]                  from /usr/include/libtorrent/torrent_handle.hpp:43,
[   62s]                  from src/torrent.h:13,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:584:18: note: candidate: template<class Y, class D> boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(boost::movelib::unique_ptr<Y, D>) [with Y = Y; D = D; T = libtorrent::torrent_info]
[   62s]      shared_ptr & operator=( boost::movelib::unique_ptr<Y, D> r )
[   62s]                   ^~~~~~~~
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:584:18: note:   template argument deduction/substitution failed:
[   62s] src/mainwindow.cpp:190:16: note:   mismatched types 'boost::movelib::unique_ptr<Y, D>' and 'libtorrent::torrent_info*'
[   62s]          p.ti = inf;
[   62s]                 ^~~
[   62s] In file included from /usr/include/boost/shared_ptr.hpp:17:0,
[   62s]                  from /usr/include/libtorrent/torrent_handle.hpp:43,
[   62s]                  from src/torrent.h:13,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:632:18: note: candidate: boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(boost::shared_ptr<T>&&) [with T = libtorrent::torrent_info]
[   62s]      shared_ptr & operator=( shared_ptr && r ) BOOST_NOEXCEPT
[   62s]                   ^~~~~~~~
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:632:18: note:   no known conversion for argument 1 from 'libtorrent::torrent_info*' to 'boost::shared_ptr<libtorrent::torrent_info>&&'
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:639:18: note: candidate: template<class Y> boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(boost::shared_ptr<Y>&&) [with Y = Y; T = libtorrent::torrent_info]
[   62s]      shared_ptr & operator=( shared_ptr<Y> && r ) BOOST_NOEXCEPT
[   62s]                   ^~~~~~~~
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:639:18: note:   template argument deduction/substitution failed:
[   62s] src/mainwindow.cpp:190:16: note:   mismatched types 'boost::shared_ptr<X>' and 'libtorrent::torrent_info*'
[   62s]          p.ti = inf;
[   62s]                 ^~~
[   62s] In file included from /usr/include/boost/shared_ptr.hpp:17:0,
[   62s]                  from /usr/include/libtorrent/torrent_handle.hpp:43,
[   62s]                  from src/torrent.h:13,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:649:18: note: candidate: boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(boost::detail::sp_nullptr_t) [with T = libtorrent::torrent_info; boost::detail::sp_nullptr_t = std::nullptr_t]
[   62s]      shared_ptr & operator=( boost::detail::sp_nullptr_t ) BOOST_NOEXCEPT // never throws
[   62s]                   ^~~~~~~~
[   62s] /usr/include/boost/smart_ptr/shared_ptr.hpp:649:18: note:   no known conversion for argument 1 from 'libtorrent::torrent_info*' to 'boost::detail::sp_nullptr_t {aka std::nullptr_t}'
[   62s] src/mainwindow.cpp:193:40: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]          mapTorrent[main->torrent->name()] = main;
[   62s]                                         ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp: In member function 'void MainWindow::updateInform()':
[   62s] src/mainwindow.cpp:203:69: warning: 'const libtorrent::torrent_info& libtorrent::torrent_handle::get_torrent_info() const' is deprecated [-Wdeprecated-declarations]
[   62s]      libtorrent::torrent_info info = main->torrent->get_torrent_info();
[   62s]                                                                      ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:920:23: note: declared here
[   62s]    const torrent_info& get_torrent_info() const;
[   62s]                        ^~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp: In member function 'void MainWindow::checkKeys()':
[   62s] src/mainwindow.cpp:249:71: warning: 'int libtorrent::session_handle::download_rate_limit() const' is deprecated [-Wdeprecated-declarations]
[   62s]          session->set_download_rate_limit(session->download_rate_limit() + 10000);
[   62s]                                                                        ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:887:7: note: declared here
[   62s]    int download_rate_limit() const;
[   62s]        ^~~~~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp:249:80: warning: 'void libtorrent::session_handle::set_download_rate_limit(int)' is deprecated [-Wdeprecated-declarations]
[   62s]          session->set_download_rate_limit(session->download_rate_limit() + 10000);
[   62s]                                                                                 ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:902:8: note: declared here
[   62s]    void set_download_rate_limit(int bytes_per_second);
[   62s]         ^~~~~~~~~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp:251:71: warning: 'int libtorrent::session_handle::download_rate_limit() const' is deprecated [-Wdeprecated-declarations]
[   62s]          session->set_download_rate_limit(session->download_rate_limit() - 10000);
[   62s]                                                                        ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:887:7: note: declared here
[   62s]    int download_rate_limit() const;
[   62s]        ^~~~~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp:251:80: warning: 'void libtorrent::session_handle::set_download_rate_limit(int)' is deprecated [-Wdeprecated-declarations]
[   62s]          session->set_download_rate_limit(session->download_rate_limit() - 10000);
[   62s]                                                                                 ^
[   62s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   62s]                  from src/mainwindow.h:36,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/session_handle.hpp:902:8: note: declared here
[   62s]    void set_download_rate_limit(int bytes_per_second);
[   62s]         ^~~~~~~~~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp: In member function 'void MainWindow::updateTable()':
[   62s] src/mainwindow.cpp:273:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
[   62s]      for (int i = 0; i < torrents.size(); i++) {
[   62s]                      ~~^~~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp:274:101: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]          ui->tableWidget->setItem(i, 0, new QTableWidgetItem(QString::fromStdString(torrents[i].name())));
[   62s]                                                                                                      ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp:281:106: warning: 'const libtorrent::torrent_info& libtorrent::torrent_handle::get_torrent_info() const' is deprecated [-Wdeprecated-declarations]
[   62s]          ui->tableWidget->setItem(i, 7, new QTableWidgetItem(QString::number(torrents[i].get_torrent_info().total_size() / 1000000)));
[   62s]                                                                                                           ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:920:23: note: declared here
[   62s]    const torrent_info& get_torrent_info() const;
[   62s]                        ^~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp:288:83: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
[   62s]          if ((ui->tableWidget->currentRow() < 0) || (ui->tableWidget->currentRow() >= torrents.size())) {
[   62s]                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
[   62s] src/mainwindow.cpp:294:84: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]          ui->downloadPathLabel->setText("Download path: " + mapTorrent[active->name()]->downloadPath);
[   62s]                                                                                     ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp:295:74: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]          ui->mountLabel->setText("Mounted to: " + mapTorrent[active->name()]->mountPath);
[   62s]                                                                           ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp:296:37: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]          if (mapTorrent[active->name()]->mountStatus())
[   62s]                                      ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp: In member function 'void MainWindow::realRemount(QString)':
[   62s] src/mainwindow.cpp:311:76: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]      mapTorrent[session->get_torrents()[ui->tableWidget->currentRow()].name()]->setMountPath(mount);
[   62s]                                                                             ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp:312:76: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]      mapTorrent[session->get_torrents()[ui->tableWidget->currentRow()].name()]->remount();
[   62s]                                                                             ^
[   62s] In file included from src/torrent.h:13:0,
[   62s]                  from src/mainwindow.h:21,
[   62s]                  from src/mainwindow.cpp:1:
[   62s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   62s]    std::string name() const;
[   62s]                ^~~~
[   62s] src/mainwindow.cpp: In member function 'void MainWindow::remountRequest()':
[   62s] src/mainwindow.cpp:317:132: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   62s]          SetMountPathDialog *dialog = new SetMountPathDialog(mapTorrent[session->get_torrents()[ui->tableWidget->currentRow()].name()]->mountPath);
[   62s]                                                                                                                                     ^
[   62s] In file included from src/torrent.h:13:0,
[   63s]                  from src/mainwindow.h:21,
[   63s]                  from src/mainwindow.cpp:1:
[   63s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   63s]    std::string name() const;
[   63s]                ^~~~
[   63s] src/mainwindow.cpp: In member function 'void MainWindow::addTorrentByName(QString)':
[   63s] src/mainwindow.cpp:338:67: warning: 'libtorrent::torrent_info::torrent_info(const libtorrent::entry&)' is deprecated [-Wdeprecated-declarations]
[   63s]      libtorrent::torrent_info *inf = new libtorrent::torrent_info(e);
[   63s]                                                                    ^
[   63s] In file included from src/mainwindow.h:34:0,
[   63s]                  from src/mainwindow.cpp:1:
[   63s] /usr/include/libtorrent/torrent_info.hpp:390:3: note: declared here
[   63s]    torrent_info(entry const& torrent_file);
[   63s]    ^~~~~~~~~~~~
[   63s] src/mainwindow.cpp:340:84: error: no matching function for call to 'libtorrent::session::add_torrent(libtorrent::torrent_info*&, std::__cxx11::string, libtorrent::entry&)'
[   63s]              session->add_torrent(inf, (s.value("path").toString()).toStdString(), e);
[   63s]                                                                                     ^
[   63s] In file included from /usr/include/libtorrent/session.hpp:53:0,
[   63s]                  from src/mainwindow.h:36,
[   63s]                  from src/mainwindow.cpp:1:
[   63s] /usr/include/libtorrent/session_handle.hpp:215:18: note: candidate: libtorrent::torrent_handle libtorrent::session_handle::add_torrent(const libtorrent::add_torrent_params&)
[   63s]    torrent_handle add_torrent(add_torrent_params const& params);
[   63s]                   ^~~~~~~~~~~
[   63s] /usr/include/libtorrent/session_handle.hpp:215:18: note:   candidate expects 1 argument, 3 provided
[   63s] /usr/include/libtorrent/session_handle.hpp:217:18: note: candidate: libtorrent::torrent_handle libtorrent::session_handle::add_torrent(const libtorrent::add_torrent_params&, libtorrent::error_code&)
[   63s]    torrent_handle add_torrent(add_torrent_params const& params, error_code& ec);
[   63s]                   ^~~~~~~~~~~
[   63s] /usr/include/libtorrent/session_handle.hpp:217:18: note:   candidate expects 2 arguments, 3 provided
[   63s] /usr/include/libtorrent/session_handle.hpp:224:18: note: candidate: libtorrent::torrent_handle libtorrent::session_handle::add_torrent(const libtorrent::torrent_info&, const string&, const libtorrent::entry&, libtorrent::storage_mode_t, bool, libtorrent::storage_constructor_type)
[   63s]    torrent_handle add_torrent(
[   63s]                   ^~~~~~~~~~~
[   63s] /usr/include/libtorrent/session_handle.hpp:224:18: note:   no known conversion for argument 1 from 'libtorrent::torrent_info*' to 'const libtorrent::torrent_info&'
[   63s] /usr/include/libtorrent/session_handle.hpp:234:18: note: candidate: libtorrent::torrent_handle libtorrent::session_handle::add_torrent(const char*, const libtorrent::sha1_hash&, const char*, const string&, const libtorrent::entry&, libtorrent::storage_mode_t, bool, libtorrent::storage_constructor_type, void*)
[   63s]    torrent_handle add_torrent(
[   63s]                   ^~~~~~~~~~~
[   63s] /usr/include/libtorrent/session_handle.hpp:234:18: note:   candidate expects 9 arguments, 3 provided
[   63s] src/mainwindow.cpp:344:21: warning: 'bool libtorrent::torrent_handle::is_paused() const' is deprecated [-Wdeprecated-declarations]
[   63s]      if (h.is_paused())
[   63s]                      ^
[   63s] In file included from src/torrent.h:13:0,
[   63s]                  from src/mainwindow.h:21,
[   63s]                  from src/mainwindow.cpp:1:
[   63s] /usr/include/libtorrent/torrent_handle.hpp:942:8: note: declared here
[   63s]    bool is_paused() const;
[   63s]         ^~~~~~~~~
[   63s] src/mainwindow.cpp:347:23: warning: 'std::__cxx11::string libtorrent::torrent_handle::name() const' is deprecated [-Wdeprecated-declarations]
[   63s]      mapTorrent[h.name()] = new Torrent(s.value("path").toString(), "/", h, this);
[   63s]                        ^
[   63s] In file included from src/torrent.h:13:0,
[   63s]                  from src/mainwindow.h:21,
[   63s]                  from src/mainwindow.cpp:1:
[   63s] /usr/include/libtorrent/torrent_handle.hpp:916:15: note: declared here
[   63s]    std::string name() const;
[   63s]                ^~~~
[   63s] src/main.cpp: In function 'void sigtermListened(int)':
[   63s] src/main.cpp:39:26: warning: unused parameter 'sig' [-Wunused-parameter]
[   63s]  void sigtermListened(int sig) {
[   63s]                           ^~~
[   63s] src/main.cpp: In function 'int main(int, char**)':
[   63s] src/main.cpp:60:19: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
[   63s]          argv[1] = "-g";
[   63s]                    ^~~~

**Comment by vtyulb** [comment]
Знакомые люди :-)

Конечно проект заброшен, но это не значит, что он имеет право не работать. Выглядит будто кто-то обновил libtorrent, а я, для удобства, юзал deprecated методы...

Завтра посмотрю что к чему.

**Comment by vtyulb** [comment]
Пофиксил все ошибки компиляции, qbittorrent точно так же сломали пару месяцев назад в арче.
Только релиз версия падает при запуске. Дебаг версия работает хорошо, что странно. Вечером попробую разобраться.

**Comment by vtyulb** [comment]
All fixed

**Comment by DAP-DarkneSS** [comment]
Thank you very much!
